{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
type: Opaque
data:
  password: {{ .Values.secrets.password | b64enc | quote }}
  username: {{ .Values.secrets.username | b64enc | quote }}
  dbname: {{ .Values.secrets.dbname | b64enc | quote }}
{{- end }}
