apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hasura-chart.fullname" . }}
  labels:
    {{- include "hasura-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hasura-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hasura-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "hasura-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: dburl
                  name: {{ include "hasura-chart.fullname" . }}
            - name: HASURA_GRAPHQL_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: {{ include "hasura-chart.fullname" . }}
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: {{ .Values.env.enableConsole | quote }}
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              value: {{ .Values.env.enabledLogTypes | quote }}
            {{- if .Values.auth.jwt.enabled }}
            - name: HASURA_GRAPHQL_JWT_SECRET
              value: {{ .Values.env.jwtSecret | quote }}
            {{- end }}
            {{- if .Values.auth.hook.enabled }}
            - name: HASURA_GRAPHQL_AUTH_HOOK
              value: {{ .Values.env.authHook | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
