apiVersion: v1
kind: Service
metadata:
  name: {{ include "hasura-chart.fullname" . }}
  labels:
    {{- include "hasura-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    {{- include "hasura-chart.selectorLabels" . | nindent 4 }}
